test_that("validated grouped grids are promoted with bounded inference", {
  methods <- c("dp_lmm_grid", "dp_glmm_grid", "dp_cox_grid")
  status <- ds.vertMethodStatus(methods)
  expect_setequal(status$method, methods)
  expect_true(all(status$status == "promoted"))
  expect_true(all(status$release_contract == "formal_sticky_synopsis_artifact"))
  expect_true(all(status$numeric_contract == "separate_integer_dp_contract"))
  expect_false(any(status$currently_numerically_certified))
  expect_false(any(status$may_report_numerically_certified))
  expect_true(all(grepl("no standard errors", status$principal_limitation, fixed = TRUE)))
  expect_true(all(grepl("Grid-resolution-limited", status$principal_limitation, fixed = TRUE)))
  expect_match(ds.vertMethodStatus("dp_cox_grid")$safe_scope,
               "400 aligned observations", fixed = TRUE)
  inventory <- .dsvert_capsule_method_inventory()
  rows <- inventory[inventory$method %in% methods, , drop = FALSE]
  expect_equal(nrow(rows), 3L)
  expect_true(all(rows$current_route_status == "formal_sticky_synopsis_artifact"))
  expect_true(all(rows$migration_feasibility == "synopsis_release_implemented"))
  expect_true(all(rows$artifact_implementation_state == "validated_synopsis_adapter_implemented"))
  expect_true(all(rows$inference_implementation_state == "synopsis_postprocess_implemented"))
  expect_true(all(vapply(rows$legacy_remote_call_evidence, nrow, integer(1L)) == 0L))
})

test_that("GEE remains quarantined while evidence is running", {
  status <- ds.vertMethodStatus("dp_gee_grid")
  expect_identical(status$status, "quarantine")
  expect_identical(status$release_contract, "disclosure_safe_protocol_no_statistic")
  expect_identical(status$numeric_contract, "not_applicable_no_statistic")
  inventory <- .dsvert_capsule_method_inventory()
  row <- inventory[inventory$method == "dp_gee_grid", , drop = FALSE]
  expect_identical(row$current_route_status, "signed_workload_unavailable_quarantine")
  expect_identical(row$artifact_implementation_state, "secure_artifact_not_implemented")
  registry <- ds.vertMethodStatus()
  expect_equal(nrow(registry), 114L)
  expect_equal(sum(registry$status == "promoted"), 111L)
  expect_equal(sum(registry$status == "provisional"), 2L)
  expect_identical(registry$method[registry$status == "quarantine"], "dp_gee_grid")
})
